allprojects {
    repositories {
        google()
        mavenCentral()
        // JitPack compila i tag da GitHub su richiesta: artefatti non firmati e tag
        // ricreabili. Confinato all'unico gruppo che ne ha bisogno (XXPermissions),
        // cosi' non puo' servire nessun'altra coordinata.
        exclusiveContent {
            forRepository {
                maven { url 'https://jitpack.io' }
            }
            filter {
                includeGroup 'com.github.getActivity'
            }
        }
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
