#!/bin/bash

set -e

if [ "$1" = configure ]; then

	INITSYS=$(ls -al /proc/1/exe | awk -F' ' '{print $NF}' | awk -F'/' '{print $NF}')
	ln -f -s /usr/share/clantodesk/clantodesk /usr/bin/clantodesk

	if [ "systemd" == "$INITSYS" ]; then

		if [ -e /etc/systemd/system/clantodesk.service ]; then
			rm /etc/systemd/system/clantodesk.service /usr/lib/systemd/system/clantodesk.service /usr/lib/systemd/user/clantodesk.service >/dev/null  2>&1
		fi
		mkdir -p /usr/lib/systemd/system/
		cp /usr/share/clantodesk/files/systemd/clantodesk.service /usr/lib/systemd/system/clantodesk.service
		# try fix error in Ubuntu 18.04
		# Failed to reload clantodesk.service: Unit clantodesk.service is not loaded properly: Exec format error.
		# /usr/lib/systemd/system/clantodesk.service:10: Executable path is not absolute: pkill -f "clantodesk --"
		if [ -e /usr/bin/pkill ]; then
			sed -i "s|pkill|/usr/bin/pkill|g" /usr/lib/systemd/system/clantodesk.service
		fi
		systemctl daemon-reload
		systemctl enable clantodesk
		systemctl start clantodesk
	fi
fi
